# Generated by Django 4.2.5 on 2023-09-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DescricaoCha',
            fields=[
                ('id_descricao', models.AutoField(primary_key=True, serialize=False)),
                ('conhecimentos', models.TextField(max_length=255)),
                ('habilidades', models.TextField(max_length=255)),
                ('atitudes', models.TextField(max_length=255)),
                ('cargo', models.TextField(max_length=255)),
                ('nivel', models.TextField(max_length=255)),
            ],
        ),
    ]
